import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Script from "next/script";

import { auth, signOut } from "~/app/utils/auth";
import Navbar from "./components/Navbar.dashboard";
import "./style.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  async function handleSignOut() {
    "use server";
    console.log("Signing out");
    await signOut();
  }
  return (
    <html lang="en" className="h-full">
      <head>
        <Script
          src="https://kit.fontawesome.com/4b1731d176.js"
          crossOrigin="anonymous"
        />
      </head>

      <body
        className={`${inter.className} h-full bg-gradient-to-tr  from-purple-100 to-blue-50`}
      >
        <header className="bg-gray-950 p-4">
          <div className="container mx-auto">
            <h1 className="text-white text-2xl">My Website</h1>
          </div>
        </header>
        <Navbar />
        <main className="h-full  ">{children}</main>
        <footer className="bg-gray-800 p-4">
          <div className="container mx-auto text-center text-white">
            &copy; 2023 LVH
          </div>
        </footer>
      </body>
    </html>
  );
}
